# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8763/eureka/
  instance:
    preferIpAddress: true

# HTTP Server
server:
  port: 5555   # HTTP (Tomcat) port
  contextPath: /configservice